name: Sanity CI/CD

on:
  push:
    branches: [main]

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli

      - name: Run Sanity Commands
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }} # Store token in GitHub Secrets
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }} # Your project ID
          SANITY_DATASET: production # Your dataset name
        run: |
          sanity init --yes --project $SANITY_PROJECT_ID --dataset $SANITY_DATASET
          sanity deploy --force  # --force skips confirmation prompts
